#!/bin/sh

dir=".X"
files=".xinitrc:initrc .Xdefaults:defaults .Xmodmap:modmap .xbindkeysrc:keybindings"

for f in $files; do
	link=$(echo $f | cut -d: -f1)
	file=$(echo $f | cut -d: -f2)
	rm -f ../$link
	ln -s $dir/$file ../$link
done
