#!/bin/sh

if [ -f "/etc/X11/xinit/.Xresources" ]; then
  xrdb -merge /etc/X11/xinit/.Xresources
fi
if [ -f "$XDG_CONFIG_HOME/X11/defaults" ]; then
  xrdb -merge "$XDG_CONFIG_HOME/X11/defaults"
fi
setxkbmap -layout fr
if [ -f "/etc/X11/xinit/.Xmodmap" ]; then
  xmodmap /etc/X11/xinit/.Xmodmap
fi
if [ -f "$XDG_CONFIG_HOME/X11/modmap" ]; then
  xmodmap "$XDG_CONFIG_HOME/X11/modmap"
fi

xsetroot -cursor_name left_ptr

# Source system xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

feh --bg-scale "$HOME/.xmonad/wallpaper.jpg"

touchegg &
stalonetray --config "$HOME/.config/stalonetrayrc" &
compton -b --config "$HOME/.config/comptonrc"
cbatticon -r 10 >/dev/null 2>&1 &

exec xmonad
