#!/bin/bash

shopt -s nullglob
files=(/sys/class/power_supply/*/capacity)
percent="$(awk '{cap += $1} END {printf "%3.0f", cap / '"${#files[@]}"'}' ${files[@]})"
state="$(sort -u /sys/class/power_supply/*/status)"

icon=''
if [ "$(cat /sys/class/power_supply/AC/online)" = 1 ]; then
	icon=''
fi

# $state only contains Full when all batteries are full
case "$state" in
	Full) percent=100;;
esac

exec printf "<span rise='-2500'>%s</span>%3d%%" "$icon" "$percent"
