#!/bin/sh

configdir="${XDG_CONFIG_HOME:-"$HOME/.config"}"/run
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
fi
libexec="$HOME/.local/libexec/sway"

select() {
	fzf --inline-info \
		--layout=reverse \
		--margin=1 \
		--header=--- \
		--preview-window=down \
		--preview='$(echo {} | cut -d: -f2-) --help' \
		--history="$cachedir/sway-run-history" \
		--history-size=128 \
		--bind page-up:preview-page-up \
		--bind page-down:preview-page-down \
		--no-clear
}

prepend() {
	sed -e 's|^|'"$1"'|' $2
}

trimspace() {
	sed -E -e 's/^\s*//' -e 's/\s*$//'
}

actions() {
	if [ -x "$configdir/actions" ]; then
		actions=$(grep -E -o '\s*(function\s)?\s*actions_\w*\s*\(\)'    \
				"$configdir/actions"                                    \
			| sed -E -e 's/actions_(\w*)\s*\(\)/\1/g'                   \
			| sort -u)
		for a in $actions; do
			if command -V "entries_$a" >/dev/null 2>&1; then
				"entries_$a"
			else
				echo $a
			fi | prepend 'action: '
		done
		unset a;
	fi
	cat
}

desktop_get () {
	awk -F= -v section="[$2]" -v variable="$3" '
		$0 == section { in_section = 1; next }
		in_section && $1 == variable {
			sub(/^[[:space:]]+/, "")
			for (i=2; i<=NF; i++) print $i
			exit
		}
		in_section && $1 == "" { exit 1 }
	' "$1"
}

apps() {
	if [ -d "/usr/share/applications/" ]; then
		for f in /usr/share/applications/?*.desktop; do
			desktop_get "$f" 'Desktop Entry' Name
		done | prepend 'app: '
		unset f
	fi
	cat
}

wm() {
	swaymsg -t get_workspaces \
		| jq -r '.[].name' \
		| prepend 'workspace: '
	swaymsg -t get_tree \
		| ~/.local/libexec/sway/list-windows.jq \
		| prepend 'window: '
	cat
}

executables() {
	( IFS=:; find $PATH -executable -type f -printf '%f\n' ) | sort -u | prepend 'run: '
}

workspace_from_name() {
	wmctrl -d | grep -E "$1$" | grep -E -o '^[[:digit:]]+'
}

run() {
	IFS=''
	select="$(head -n1)"
	type="$(echo $select | cut -d: -f1)"
	val="$(echo $select | cut -d: -f2- | trimspace)"
	unset IFS

	case $type in
		action|act|a)
			eval actions_$val &;;
		run|r)
			exec swaymsg exec $val;;
		app)
			launch=$(grep -E "^Name=\s*$val\s*" -r "/usr/share/applications" \
				| cut -d: -f1)
			eval exec $(desktop_get "$launch" 'Desktop Entry' Exec \
				| sed -e 's/^Exec=//' -e 's/%[fFuUdDnNickvm]//g') &
			;;
		workspace|work)
			exec swaymsg workspace $val;;
		window|win)
			ws="$(echo "$val" | grep -Eo '^\[[^]]+\]' | tr -d '\[\]')"
			exec swaymsg workspace $ws;;
	esac
}

[ -x "$configdir/actions" ] && . $configdir/actions >/dev/null 2>&1

executables | actions | apps | wm | select | run
